config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # get 'cart/index'
  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/cart', to: 'cart#index', as: 'cart'

  resources :teams, only: %i[index show] do
    collection do
      get 'search_results'
    end
  end

  resources :jerseys, only: %i[index show new_jerseys updated_jerseys] do
    collection do
      get 'search_results'
      get 'new_jerseys'
      get 'updated_jerseys'
    end
  end

  post 'jerseys/add_to_cart/:id', to: 'jerseys#add_to_cart', as: 'add_to_cart'
  delete 'cart/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  # delete 'jerseys/remove_from_cart/:id', to: 'jerseys#remove_from_cart', as: 'remove_from_cart'

  root 'teams#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  belongs_to :province

  validates :name, :email, :phone, :postalcode, :address, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/jersey.rb
# frozen_string_literal: true

class Jersey < ApplicationRecord
  has_many :jersey_orders
  has_many :orders, through: :jersey_orders

  belongs_to :team

  has_one_attached :image

  validates :name, :description, :price, presence: true
  validates :price, numericality: { only_decimal: true }
end

app/models/jersey_order.rb
# frozen_string_literal: true

class JerseyOrder < ApplicationRecord
  belongs_to :jersey
  belongs_to :order

  validates :quantity, :unit_price, presence: true
  validates :unit_price, numericality: { only_decimal: true }
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :jersey_orders
  has_many :jerseys, through: :jersey_orders

  validates :subtotal, :total, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000 }
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  validates :title, :content, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_many :jerseys

  has_one_attached :image

  validates :name, presence: true

  # def thumbnail
  #   image.variant(resize: '300x300!').processed
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  before_action :initialize_session
  before_action :load_cart

  def index; end

  def remove_from_cart
    id = params[:id].to_i

    session[:cart].delete(id)
    redirect_to cart_path
  end

  private

  def initialize_session
    session[:cart] ||= []
  end

  def load_cart
    @cart = Jersey.find(session[:cart])
  end
end

app/controllers/jerseys_controller.rb
# frozen_string_literal: true

require 'pagy/extras/bootstrap'

class JerseysController < ApplicationController
  before_action :initialize_session
  before_action :load_cart

  def index
    @pagy, @jerseys = pagy(Jersey.all, items: 10)
    @showteams = Team.all

    add_breadcrumb 'home', :root_path
    add_breadcrumb '// jerseys', :jerseys_path
  end

  def show
    @jersey = Jersey.find(params[:id])
    @team = Team.find(@jersey.team_id)

    add_breadcrumb 'home', :root_path
    add_breadcrumb '// teams', :teams_path
    add_breadcrumb '// ' + @team.name, :team_path
    add_breadcrumb '// ' + @jersey.name, :jersey_path
  end

  def new_jerseys
    @pagy, @jerseys = pagy(Jersey.where('created_at > ?', 45.days.ago), items: 5)
  end

  def updated_jerseys
    @pagy, @jerseys = pagy(Jersey.where('updated_at > ?', 7.days.ago), items: 5)
  end

  def search_results
    @query = params[:query]
    @team = params[:team]

    @jerseys = if @team.empty?
                 Jersey.where('name LIKE ?', "%#{@query}%")
               else
                 Jersey.where('name LIKE ? AND team_id LIKE ?',
                              "%#{@query}%", @team.to_s)
               end
  end

  def add_to_cart
    id = params[:id].to_i

    flash[:notice] = 'Jersey successfully added to cart.'

    session[:cart] << id unless session[:cart].include?(id)
    redirect_to jerseys_path
  end

  def remove_from_cart
    id = params[:id].to_i

    session[:cart].delete(id)
    redirect_to jerseys_path
  end

  private

  def initialize_session
    session[:cart] ||= []
  end

  def load_cart
    @cart = Jersey.find(session[:cart])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def contact
    @contact = Page.where('title LIKE ?', 'contact')
  end

  def about
    @about = Page.where('title LIKE ?', 'about')
  end
end

app/controllers/team_controller.rb
# frozen_string_literal: true

class TeamController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

require 'pagy/extras/bootstrap'

class TeamsController < ApplicationController
  def index
    @pagy, @teams = pagy(Team.all, items: 5)

    add_breadcrumb 'home', :root_path
    add_breadcrumb '// teams', :teams_path
  end

  def show
    @team = Team.find(params[:id])

    add_breadcrumb 'home', :root_path
    add_breadcrumb '// teams', :teams_path
    add_breadcrumb ' // ' + @team.name, :team_path
  end

  def search_results
    @query = params[:query]
    @teams = Team.where('name LIKE ?', "%#{@query}%")
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/jerseys_helper.rb
module JerseysHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/cart/index.html.erb
<div class="container-fluid">
  <summary>Shopping Cart</summary>
  <% if @cart.empty? %>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <p>No items in cart</p>
  <% else %>
    <ul>
      <% @cart.each do |jersey| %>
        <li><%= jersey.name %> - <%= link_to 'remove', remove_from_cart_path(jersey), method: :delete %>     <%= number_to_currency jersey.price %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/jerseys/_jersey.html.erb
<% @jerseys.each do |jersey| %>
  <div class="card">
  <%= image_tag url_for(jersey.image), class: 'card-img-top', alt: jersey %>
  <div class="card-body">
    <%= link_to jersey.name, jersey, class: 'card-text' %>
    <%= number_to_currency jersey.price, class: 'card-text' %>
    <% if @cart.include?(jersey) %>
      <p>Already in your cart</p>
    <% else %>
      <p><%= link_to 'add to cart', add_to_cart_path(jersey.id), method: :post, class: 'card-text' %></p>
    <% end %>
  </div>
  </div>
<% end %>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
x<% end %>

app/views/jerseys/_new_jerseys.html.erb
<% @jerseys.each do |jersey| %>
  <div class="card">
  <%= image_tag url_for(jersey.image), class: 'card-img-top', alt: jersey %>
  <div class="card-body">
    <%= link_to jersey.name, jersey, class: 'card-text' %>
    <%= number_to_currency jersey.price, class: 'card-text' %>
    <% if @cart.include?(jersey) %>
      <p>Already in your cart</p>
    <% else %>
      <p><%= link_to 'add to cart', add_to_cart_path(jersey.id), method: :post, class: 'btn btn-info' %></p>
    <% end %>
  </div>
  </div>
<% end %>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/jerseys/index.html.erb
<%= form_with(url: search_results_jerseys_path, method: "get", local: true) do %>
  <%= select_tag :team, options_from_collection_for_select(Team.all, "id", "name"), include_blank: "ALL" %>
  <%= text_field_tag(:query, "", placeholder:"Search...") %>
  <%= submit_tag("Search") %>
<% end %>

<%= render 'layouts/alerts' %>

<div class="card-deck">
  <%= render partial: 'jersey' %>
</div>

<%= pagy_bootstrap_nav(@pagy).html_safe %>

app/views/jerseys/new_jerseys.html.erb
<%= form_with(url: search_results_jerseys_path, method: "get", local: true) do %>
  <%= select_tag :team, options_from_collection_for_select(Team.all, "id", "name"), include_blank: "ALL" %>
  <%= text_field_tag(:query, "", placeholder:"Search...") %>
  <%= submit_tag("Search") %>
<% end %>

<%= render 'layouts/alerts' %>

<%= link_to 'All Products', jerseys_path, class:'btn btn-info' %>
<%= link_to 'New', new_jerseys_jerseys_path, class:'btn btn-info' %>
<%= link_to 'Recently Updated', updated_jerseys_jerseys_path, class:'btn btn-info' %>

<p></p>
<div class="card-deck">
  <%= render partial: 'new_jerseys' %>
</div>

<%= pagy_bootstrap_nav(@pagy).html_safe %>

app/views/jerseys/search_results.html.erb
<p><%= pluralize(@jerseys.size, 'result') %> for '<%= @query %>'</p>

<div class="card-deck">
  <% @jerseys.each do |jersey| %>
    <div class="card">
    <%= image_tag url_for(jersey.image), class: 'card-img-top', alt: jersey %>
    <div class="card-body">
      <%= link_to jersey.name, jersey, class: 'card-text' %>
    </div>
    </div>
  <% end %>
</div>

app/views/jerseys/show.html.erb
<%= image_tag url_for(@jersey.image), class: 'img-thumbnail', alt: 'jersey' %>
<p><%= @jersey.name %></p>
<p><%= number_to_currency @jersey.price %></p>
<button type="button" class="btn btn-info">Add to Cart</button>

app/views/jerseys/updated_jerseys.html.erb
<%= form_with(url: search_results_jerseys_path, method: "get", local: true) do %>
  <%= select_tag :team, options_from_collection_for_select(Team.all, "id", "name"), include_blank: "ALL" %>
  <%= text_field_tag(:query, "", placeholder:"Search...") %>
  <%= submit_tag("Search") %>
<% end %>

<%= render 'layouts/alerts' %>

<%= link_to 'All Products', jerseys_path, class:'btn btn-info' %>
<%= link_to 'New', new_jerseys_jerseys_path, class:'btn btn-info' %>
<%= link_to 'Recently Updated', updated_jerseys_jerseys_path, class:'btn btn-info' %>

<p></p>
<div class="card-deck">
  <% @jerseys.each do |jersey| %>
  <div class="card">
  <%= image_tag url_for(jersey.image), class: 'card-img-top', alt: jersey %>
  <div class="card-body">
    <%= link_to jersey.name, jersey, class: 'card-text' %>
    <%= number_to_currency jersey.price, class: 'card-text' %>
    <% if @cart.include?(jersey) %>
      <p>Already in your cart</p>
    <% else %>
      <p><%= link_to 'add to cart', add_to_cart_path(jersey.id), method: :post, class: 'card-text' 'btn btn-info', type: 'button' %></p>
    <% end %>
  </div>
  </div>
<% end %>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
</div>

<%= pagy_bootstrap_nav(@pagy).html_safe %>